### ISSUE TITLE
Request for Detailed Instructions to get Spotify + SpotX up and running. 

### ISSUE THREAD

**Issue by BashBandito** [oskardotglobal/.dotfiles#1]
Hi Oskar,

Thank you for sharing your dotfiles and for trying to help—it's greatly appreciated!

I noticed that the structure of your repository has changed since the last version, and the `packages/spotify` folder seems to be missing. I followed the non-flakes instructions in the updated README, but I ran into errors during the test build. Despite adding Spotify to my configuration and including the overlay code, it’s not working as expected.

As a newcomer to NixOS and not very experienced with programming, I would greatly benefit from a more detailed, step-by-step guide. Could you please provide clear instructions for adding Spotify to my user packages, rather than system-wide? I currently use a single `configuration.nix` file for everything, including home-manager, and I’m not utilizing flakes. 

I hope I'm not asking for too much. I’ve made several attempts to figure this out on my own, and while I’m eager to learn, I’m finding it challenging. Any guidance you can provide would be incredibly helpful.

Thanks again

**Comment by oskardotglobal** [comment]
Sure, what's your error?

**Comment by oskardotglobal** [comment]
I mean, the ads during listening are not that rare, so if it didn't work you should notice whilst using it.

**Comment by oskardotglobal** [comment]
You don't have to do anything, I'll periodically update the spotx script version, but spotify will update normally along with your system.

**Comment by oskardotglobal** [comment]
I've just updated the script since it seems to be broken right now, is/has it been working for you?

**Comment by oskardotglobal** [comment]
Well, the spotx script *should* run normally so I don't see why the visual changes shouldn't be there

Or is there a flag that needs to be passed to the script? If so I can add that

**Comment by oskardotglobal** [comment]
Yeah, that's the one I use.

**Comment by oskardotglobal** [comment]
Oh my god, I'm such an idiot; the script wasn't running at all since I was editing the wrong phase of the package. I've gone ahead and fixed that.
